language: python

before_install:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install pymdown-extensions

script:
  - mkdocs build

after_success:
  - echo "${SSH_KEY}" | base64 --decode >/tmp/ssh_key
  - chmod 600 /tmp/ssh_key
  - sha1sum  /tmp/ssh_key
  - tar cz -C site/ . | ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key ${SSH_USER}@${SSH_SERVER} "tar xz -C /var/www/developers/"
