site_name: Developer Portal
site_url: https://workshopbutler.com/developers
theme:
  name: 'material'
  custom_dir: 'theme'
  font: 'Arial'
  favicon: 'img/favicon.ico'
  palette:
    primary: 'white'
    accent: 'pink'
  feature:
    tabs: true

extra_css:
  - css/extra.css

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.snippets:
      base_path: 'docs/snippets'

google_analytics:
  - 'UA-42138624-5'
  - 'auto'

extra:
  social:
      - type: 'twitter'
        link: 'https://twitter.com/workshopbutler'
      - type: 'linkedin'
        link: 'https://www.linkedin.com/company/workshop-butler'
      - type: 'facebook'
        link: 'https://facebook.com/WorkshopButler'

pages:
- Home:
  - Home: index.md
  - Contributing: contributing.md
#- API:
#  - Reference: api/index.md
- JS Widgets:
  - Getting Started: widgets/index.md
  - Widgets:
    - Schedule: widgets/widgets/schedule.md
    - Event Page: widgets/widgets/event-page.md
    - Trainer List: widgets/widgets/trainer-list.md
    - Trainer Profile: widgets/widgets/trainer-profile.md
    - Registraiton Form: widgets/widgets/registration-form.md
    - Sidebar Event List: widgets/widgets/sidebar-event-list.md
  - Changelog: widgets/changelog.md
- Themes:
  - Getting Started: themes/index.md
  - Creating a Custom Theme: themes/custom-theme.md
  - Changelog: themes/changelog.md
- WordPress Plugin:
  - Getting Started: wordpress/index.md
  - Customising Styles: wordpress/custom-styles.md
  - Shortcodes:
    - Getting Started: wordpress/shortcodes.md
    - Page Level shortcodes: wordpress/shortcodes/page-level.md
    - Schedule Template: wordpress/shortcodes/schedule-template.md
    - Event Template: wordpress/shortcodes/event-template.md
    - Trainer List Template: wordpress/shortcodes/trainer-list-template.md
    - Trainer Profile Template: wordpress/shortcodes/trainer-profile-template.md
  - Changelog: wordpress/changelog.md
