site_name: Developer Portal
site_url: https://workshopbutler.com/developers
theme:
  name: 'material'
  custom_dir: 'theme'
  font: 'Arial'
  favicon: 'img/favicon.ico'
  palette:
    primary: 'white'
    accent: 'pink'
  feature:
    tabs: true

extra_css:
  - css/extra.css

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.snippets:
      base_path: 'docs/snippets'

google_analytics:
  - 'UA-42138624-5'
  - 'auto'

extra:
  social:
      - type: 'twitter'
        link: 'https://twitter.com/workshopbutler'
      - type: 'linkedin'
        link: 'https://www.linkedin.com/company/workshop-butler'
      - type: 'facebook'
        link: 'https://facebook.com/WorkshopButler'

pages:
- Home:
  - Home: index.md
  - Contributing: contributing.md
- API:
  - Reference: api/index.md
  - Changelog: api/changelog.md
- JS Widgets:
  - Getting Started: widgets/index.md
  - Quick Start Guide: widgets/quick-start.md
  - General Configuration: widgets/general-configs.md
  - Widgets:
    - Event Page: widgets/widgets/event-page.md
    - Event Schedule: widgets/widgets/schedule.md
    - List of Testimonials: widgets/widgets/endorsement-list.md
    - List of Trainers: widgets/widgets/trainer-list.md
    - Registration Page: widgets/widgets/registration-form.md
    - Sidebar Event List: widgets/widgets/sidebar-event-list.md
    - Trainer Profile: widgets/widgets/trainer-profile.md
  - Customisation:
    - Template Customisation: widgets/custom/template.md
    - Theme Customisation: widgets/custom/theme.md
    - Widget Customisation: widgets/custom/widget.md
  - Older versions:
    - 0.7.x:
      - Getting Started: widgets/versions/0.7.x/index.md
      - Widgets:
        - Schedule: widgets/versions/0.7.x/widgets/schedule.md
        - Event Page: widgets/versions/0.7.x/widgets/event-page.md
        - Trainer List: widgets/versions/0.7.x/widgets/trainer-list.md
        - Trainer Profile: widgets/versions/0.7.x/widgets/trainer-profile.md
        - Registration Form: widgets/versions/0.7.x/widgets/registration-form.md
        - Sidebar Event List: widgets/versions/0.7.x/widgets/sidebar-event-list.md
  - Upgrade Notes: widgets/update-notes.md
  - Changelog: widgets/changelog.md
- Themes:
  - Getting Started: themes/index.md
  - Creating a Custom Theme: themes/custom-theme.md
  - Changelog: themes/changelog.md
- WordPress Plugin:
  - Getting Started: wordpress/index.md
  - Customising Styles: wordpress/custom-styles.md
  - Shortcodes:
    - Getting Started: wordpress/shortcodes.md
    - Page Level shortcodes: wordpress/shortcodes/page-level.md
    - Schedule Template: wordpress/shortcodes/schedule-template.md
    - Event Template: wordpress/shortcodes/event-template.md
    - Registration Page Template: wordpress/shortcodes/registration-page.md
    - Trainer List Template: wordpress/shortcodes/trainer-list-template.md
    - Trainer Profile Template: wordpress/shortcodes/trainer-profile-template.md
  - Changelog: wordpress/changelog.md
